-- Evidence-based safety intelligence. Decisions are made by deterministic SQL
-- and TypeScript rules. AI-authored text is stored separately and is never an
-- input to assessment or rollup status.
create type public.safety_status as enum ('trusted', 'avoid', 'insufficient_evidence');
create type public.board_result_type as enum ('violator', 'within_limit');
create type public.rollup_period as enum ('daily', 'weekly', 'monthly');

-- Compatibility boundary with 20260826222000_speed_safety_evidence.sql.
-- That migration may already create this Flutter ingestion table in an
-- existing review branch. IF NOT EXISTS keeps this migration safe in either
-- ordering while making a fresh migration chain self-contained.
create table if not exists public.speed_samples (
  id bigint generated by default as identity primary key,
  stable_id text not null unique,
  journey_id bigint not null references public.journeys(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  recorded_at timestamptz not null,
  speed numeric(7,2) not null check (speed between 0 and 300),
  speed_limit numeric(7,2) not null check (speed_limit between 1 and 300),
  latitude double precision,
  longitude double precision,
  accuracy numeric(7,2),
  is_moving boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.speed_samples
  add column if not exists client_sample_id uuid,
  add column if not exists sequence_number integer,
  add column if not exists accepted boolean not null default true,
  add column if not exists rejection_reason text;
create unique index speed_samples_journey_client_id_idx
  on public.speed_samples(journey_id, client_sample_id) where client_sample_id is not null;
create unique index speed_samples_journey_sequence_idx
  on public.speed_samples(journey_id, sequence_number) where sequence_number is not null;

create table public.violation_episodes (
  id uuid primary key,
  journey_id bigint not null references public.journeys(id) on delete cascade,
  agency_id bigint references public.agencies(id) on delete set null,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  sample_count integer not null check (sample_count > 0),
  peak_speed_kph numeric(7,2) not null,
  average_speed_kph numeric(7,2) not null,
  duration_seconds integer not null check (duration_seconds >= 0),
  speed_limit_kph numeric(7,2) not null,
  over_by_kph numeric(7,2) not null check (over_by_kph > 0),
  created_at timestamptz not null default now(),
  check (ended_at >= started_at),
  unique (journey_id, started_at)
);

create table public.speed_reports (
  id uuid primary key default gen_random_uuid(),
  stable_id uuid not null unique,
  reporter_user_id bigint not null references public.users(id) on delete cascade,
  agency_id bigint not null references public.agencies(id) on delete cascade,
  journey_id bigint references public.journeys(id) on delete set null,
  vehicle_fingerprint text,
  observed_at timestamptz not null,
  reported_speed_kph numeric(7,2) not null check (reported_speed_kph between 0 and 300),
  speed_limit_kph numeric(7,2) not null check (speed_limit_kph between 1 and 300),
  route text,
  created_at timestamptz not null default now(),
  -- Supplied by the Edge Function as the UTC hour containing observed_at.
  report_bucket timestamptz not null,
  unique nulls not distinct (reporter_user_id, agency_id, vehicle_fingerprint, report_bucket)
);

create table public.evidence_correlations (
  id uuid primary key default gen_random_uuid(),
  episode_id uuid not null unique references public.violation_episodes(id) on delete cascade,
  telemetry_value_kph numeric(7,2) not null,
  independent_reporter_count integer not null default 0,
  robust_speed_kph numeric(7,2) not null,
  outlier_count integer not null default 0,
  capped_report_count integer not null default 0,
  method_version text not null default 'robust-weighted-v1',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.journey_safety_assessments (
  id uuid primary key default gen_random_uuid(),
  journey_id bigint not null unique references public.journeys(id) on delete cascade,
  agency_id bigint references public.agencies(id) on delete set null,
  status public.safety_status not null,
  result_type public.board_result_type not null,
  speed_limit_kph numeric(7,2) not null,
  accepted_sample_count integer not null,
  rejected_sample_count integer not null,
  episode_count integer not null,
  peak_speed_kph numeric(7,2) not null,
  average_speed_kph numeric(7,2) not null,
  duration_seconds integer not null,
  max_over_by_kph numeric(7,2) not null,
  confidence numeric(5,4) not null check (confidence between 0 and 1),
  reasons jsonb not null default '[]'::jsonb,
  rules_version text not null default 'journey-v1',
  deterministic_summary text not null,
  ai_summary text,
  ai_status text not null default 'not_requested'
    check (ai_status in ('not_requested','generated','fallback','failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.speed_board_entries (
  id uuid primary key default gen_random_uuid(),
  journey_id bigint not null unique references public.journeys(id) on delete cascade,
  assessment_id uuid not null unique references public.journey_safety_assessments(id) on delete cascade,
  agency_id bigint references public.agencies(id) on delete set null,
  result_type public.board_result_type not null,
  published_at timestamptz not null default now(),
  evidence jsonb not null,
  summary text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.agency_safety_rollups (
  id uuid primary key default gen_random_uuid(),
  agency_id bigint not null references public.agencies(id) on delete cascade,
  period public.rollup_period not null,
  period_start date not null,
  period_end date not null,
  status public.safety_status not null,
  confidence numeric(5,4) not null check (confidence between 0 and 1),
  journey_count integer not null,
  distinct_user_count integer not null,
  accepted_sample_count integer not null,
  total_duration_seconds bigint not null,
  violation_journey_count integer not null,
  violation_episode_count integer not null,
  independent_reporter_count integer not null,
  outlier_count integer not null default 0,
  weighted_speed_kph numeric(7,2),
  reasons jsonb not null default '[]'::jsonb,
  thresholds jsonb not null,
  rules_version text not null default 'agency-rollup-v1',
  deterministic_summary text not null,
  ai_summary text,
  ai_status text not null default 'not_requested'
    check (ai_status in ('not_requested','generated','fallback','failed')),
  computed_at timestamptz not null default now(),
  unique (agency_id, period, period_start)
);

create table public.user_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null references public.users(id) on delete cascade,
  event_key text not null,
  type text not null check (type in ('agency_trusted','agency_avoid')),
  title text not null,
  body text not null,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create index if not exists speed_samples_journey_time_idx on public.speed_samples(journey_id, recorded_at);
create index violation_episodes_agency_time_idx on public.violation_episodes(agency_id, started_at desc);
create index speed_reports_correlation_idx on public.speed_reports(agency_id, observed_at, vehicle_fingerprint);
create index speed_board_published_idx on public.speed_board_entries(published_at desc) where active;
create index agency_rollups_period_idx on public.agency_safety_rollups(period, period_start desc, status);
create index notifications_user_unread_idx on public.user_notifications(user_id, created_at desc) where read_at is null;

create trigger journey_safety_assessments_updated before update on public.journey_safety_assessments
for each row execute function public.set_row_updated_at();

-- The Edge Function validates the actor and computes the deterministic payload.
-- This RPC provides one atomic, idempotent write boundary at journey completion.
create or replace function public.finalize_journey_safety(
  p_actor_user_id bigint,
  p_journey_id bigint,
  p_journey_update jsonb,
  p_samples jsonb,
  p_episodes jsonb,
  p_assessment jsonb
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  owned public.journeys;
  assessment_row public.journey_safety_assessments;
  item jsonb;
begin
  select * into owned from public.journeys
    where id = p_journey_id and user_id = p_actor_user_id and deleted_at is null
    for update;
  if owned.id is null then raise exception 'journey not found'; end if;

  update public.journeys set
    status = 'completed',
    end_time = coalesce((p_journey_update->>'endTime')::timestamptz, now()),
    max_speed = coalesce((p_journey_update->>'maxSpeed')::double precision, 0),
    avg_speed = coalesce((p_journey_update->>'averageSpeed')::double precision, 0),
    distance = coalesce((p_journey_update->>'distance')::double precision, 0),
    violation_count = jsonb_array_length(p_episodes),
    score = greatest(0, 100 - (jsonb_array_length(p_episodes) * 15))
  where id = p_journey_id;

  for item in select value from jsonb_array_elements(p_samples)
  loop
    insert into public.speed_samples(
      stable_id, journey_id, user_id, client_sample_id, sequence_number, recorded_at, speed,
      speed_limit, accuracy, is_moving, latitude, longitude, accepted, rejection_reason
    ) values (
      item->>'id', p_journey_id, p_actor_user_id, (item->>'id')::uuid,
      (item->>'sequence')::integer, (item->>'recordedAt')::timestamptz,
      (item->>'speedKph')::numeric, (item->>'speedLimitKph')::numeric,
      nullif(item->>'accuracyM','')::numeric,
      coalesce((item->>'speedKph')::numeric >= 3, false),
      nullif(item->>'latitude','')::double precision,
      nullif(item->>'longitude','')::double precision,
      coalesce((item->>'accepted')::boolean, true), item->>'rejectionReason'
    ) on conflict (stable_id) do nothing;
  end loop;

  for item in select value from jsonb_array_elements(p_episodes)
  loop
    insert into public.violation_episodes(
      id, journey_id, agency_id, started_at, ended_at, sample_count,
      peak_speed_kph, average_speed_kph, duration_seconds, speed_limit_kph, over_by_kph
    ) values (
      (item->>'id')::uuid, p_journey_id, owned.agency_id,
      (item->>'startedAt')::timestamptz, (item->>'endedAt')::timestamptz,
      (item->>'sampleCount')::integer, (item->>'peakSpeedKph')::numeric,
      (item->>'averageSpeedKph')::numeric, (item->>'durationSeconds')::integer,
      (item->>'speedLimitKph')::numeric, (item->>'overByKph')::numeric
    ) on conflict (id) do nothing;
  end loop;

  insert into public.journey_safety_assessments(
    journey_id, agency_id, status, result_type, speed_limit_kph,
    accepted_sample_count, rejected_sample_count, episode_count,
    peak_speed_kph, average_speed_kph, duration_seconds, max_over_by_kph,
    confidence, reasons, deterministic_summary
  ) values (
    p_journey_id, owned.agency_id, (p_assessment->>'status')::public.safety_status,
    (p_assessment->>'resultType')::public.board_result_type,
    (p_assessment->>'speedLimitKph')::numeric,
    (p_assessment->>'acceptedSampleCount')::integer,
    (p_assessment->>'rejectedSampleCount')::integer,
    (p_assessment->>'episodeCount')::integer,
    (p_assessment->>'peakSpeedKph')::numeric,
    (p_assessment->>'averageSpeedKph')::numeric,
    (p_assessment->>'durationSeconds')::integer,
    (p_assessment->>'maxOverByKph')::numeric,
    (p_assessment->>'confidence')::numeric, p_assessment->'reasons',
    p_assessment->>'deterministicSummary'
  )
  on conflict (journey_id) do update set
    status=excluded.status, result_type=excluded.result_type,
    accepted_sample_count=excluded.accepted_sample_count,
    rejected_sample_count=excluded.rejected_sample_count,
    episode_count=excluded.episode_count, peak_speed_kph=excluded.peak_speed_kph,
    average_speed_kph=excluded.average_speed_kph, duration_seconds=excluded.duration_seconds,
    max_over_by_kph=excluded.max_over_by_kph, confidence=excluded.confidence,
    reasons=excluded.reasons, deterministic_summary=excluded.deterministic_summary
  returning * into assessment_row;

  insert into public.speed_board_entries(
    journey_id, assessment_id, agency_id, result_type, evidence, summary
  ) values (
    p_journey_id, assessment_row.id, owned.agency_id, assessment_row.result_type,
    jsonb_build_object(
      'sampleCount', assessment_row.accepted_sample_count,
      'episodeCount', assessment_row.episode_count,
      'peakSpeedKph', assessment_row.peak_speed_kph,
      'averageSpeedKph', assessment_row.average_speed_kph,
      'durationSeconds', assessment_row.duration_seconds,
      'speedLimitKph', assessment_row.speed_limit_kph,
      'maxOverByKph', assessment_row.max_over_by_kph,
      'confidence', assessment_row.confidence,
      'reasons', assessment_row.reasons
    ),
    assessment_row.deterministic_summary
  ) on conflict (journey_id) do update set
    assessment_id=excluded.assessment_id, result_type=excluded.result_type,
    evidence=excluded.evidence, summary=excluded.summary, published_at=now(), active=true;

  insert into public.audit_log(actor_user_id, action, entity_type, entity_id, details)
  values (p_actor_user_id, 'finalize_safety', 'journey', p_journey_id::text,
    jsonb_build_object('assessmentId', assessment_row.id, 'rulesVersion', assessment_row.rules_version));

  return to_jsonb(assessment_row);
end $$;

revoke all on function public.finalize_journey_safety(bigint,bigint,jsonb,jsonb,jsonb,jsonb)
  from public, anon, authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'speed_samples','violation_episodes','speed_reports','evidence_correlations',
    'journey_safety_assessments','speed_board_entries','agency_safety_rollups',
    'user_notifications'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on public.%I from anon, authenticated', table_name);
    execute format(
      'create policy %I on public.%I as restrictive for all to anon, authenticated using (false) with check (false)',
      table_name || '_edge_api_only', table_name
    );
  end loop;
end $$;

revoke all on all sequences in schema public from anon, authenticated;
